/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const dynamic _kFontPkg = null;

  static const IconData event_note =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supervisor_account =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_home =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subdirectory_arrow_left =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_answer =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_outline =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blur_circular =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blur_on =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_money =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_user =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_box =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_border =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stars =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_2 =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_outline =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_outline =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_basket =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_outline =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_1 =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large_1 =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large_outline =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_3 =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_2 =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard_2 =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_big =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_heart =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_3 =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_1 =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_4 =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_pin =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outline =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_1 =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_6 =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_circled =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torso =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_1 =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_1 =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_big =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp_1 =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonelink_lock =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_lock_portrait =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_lock_rotation =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_lock =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_wifi_4_bar_lock =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vpn_lock =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_3 =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_5 =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_1 =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_6 =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_outline =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt_outline =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2 =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_circled =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_download =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_upload =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button_checked =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button_unchecked =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_space_shuttle_2 =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_chart_bars =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt_1 =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_feed =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short_text =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_history =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_1 =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData widgets =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_wifi_4_bar =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_wifi_off =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker_phone =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_1 =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_border =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open_big =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_big =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_menu =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_neg =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_1 =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mode_edit =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_location =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_2 =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_3 =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_more =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfold_more =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_1 =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_menu_circle =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_mini =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_3 =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_1 =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_4 =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_5 =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_6 =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy_1 =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_2 =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_3 =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_4 =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_1 =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_outline =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_2 =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_4 =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_white =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_shield =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hive_emblem =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hole_ladder =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycle =
      IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      IconData(0xea88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_2 =
      IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_keys =
      IconData(0xeacc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toast =
      IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underhand =
      IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drop =
      IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi =
      IconData(0xeae5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wireless_signal =
      IconData(0xeae6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zebra_shield =
      IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_2 =
      IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_4 =
      IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet =
      IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb =
      IconData(0xf00a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty =
      IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_1 =
      IconData(0xf012, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_5 =
      IconData(0xf018, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_inv =
      IconData(0xf019, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_5 =
      IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_male =
      IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_female =
      IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_3 =
      IconData(0xf064, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt_1 =
      IconData(0xf075, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart =
      IconData(0xf07a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xf084, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_empty =
      IconData(0xf097, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_1 =
      IconData(0xf09e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_2 =
      IconData(0xf0ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_2 =
      IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_md =
      IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_left =
      IconData(0xf100, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up =
      IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down =
      IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_empty =
      IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xf132, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_empty =
      IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt =
      IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_squared =
      IconData(0xf143, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar =
      IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows =
      IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot_circled =
      IconData(0xf192, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_space_shuttle =
      IconData(0xf197, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_thin =
      IconData(0xf1db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_2 =
      IconData(0xf1eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_visa =
      IconData(0xf1f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard =
      IconData(0xf1f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_discover =
      IconData(0xf1f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_amex =
      IconData(0xf1f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_paypal =
      IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie =
      IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off =
      IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on =
      IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connectdevelop =
      IconData(0xf20e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skyatlas =
      IconData(0xf216, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_plus =
      IconData(0xf217, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_arrow_down =
      IconData(0xf218, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus =
      IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus_o =
      IconData(0xf271, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_alt =
      IconData(0xf283, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_2 =
      IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_6 =
      IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_4 =
      IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_key =
      IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_lock =
      IconData(0xf31e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_small =
      IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved =
      IconData(0xf333, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check =
      IconData(0xf33e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_x =
      IconData(0xf341, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_added =
      IconData(0xf361, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_calendar =
      IconData(0xf389, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xf38c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_1 =
      IconData(0xf38e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsaved =
      IconData(0xf3b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_3 =
      IconData(0xf3c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_2 =
      IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_alt =
      IconData(0xf3ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp_square =
      IconData(0xf40c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remottely_user =
      IconData(0xf4fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit =
      IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_friends =
      IconData(0xf500, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_lock =
      IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_shield =
      IconData(0xf505, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 =
      IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_2 =
      IconData(0xf512, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_3 =
      IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_closed =
      IconData(0xf52a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_open =
      IconData(0xf52b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check =
      IconData(0xf53c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check_alt =
      IconData(0xf53d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_contract =
      IconData(0xf56c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_africa =
      IconData(0xf57c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_americas =
      IconData(0xf57d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_asia =
      IconData(0xf57e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer_group =
      IconData(0xf5fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gremottely_host =
      IconData(0xf6e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day =
      IconData(0xf783, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_week =
      IconData(0xf784, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_europe =
      IconData(0xf7a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
