// /// Flutter icons RemottelyIcons
// /// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  RemottelyIcons
// ///      fonts:
// ///       - asset: fonts/RemottelyIcons.ttf
// ///
// ///
// /// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
// ///         Author:    Just Be Nice studio
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://www.justbenicestudio.com/
// /// * Entypo, Copyright (C) 2012 by Daniel Bruce
// ///         Author:    Daniel Bruce
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://www.entypo.com
// /// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
// ///         Author:    Dave Gandy
// ///         License:   SIL ()
// ///         Homepage:  http://fortawesome.github.com/Font-Awesome/
// /// * Material Design Icons, Copyright (C) Google, Inc
// ///         Author:    Google
// ///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
// ///         Homepage:  https://design.google.com/icons/
// /// * Typicons, (c) Stephen Hutchings 2012
// ///         Author:    Stephen Hutchings
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://typicons.com/
// /// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
// ///         Author:    Dave Gandy
// ///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
// ///         Homepage:  http://fortawesome.github.com/Font-Awesome/
// /// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
// ///         Author:    John Caserta
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
// /// * Linecons, Copyright (C) 2013 by Designmodo
// ///         Author:    Designmodo for Smashing Magazine
// ///         License:   CC BY ()
// ///         Homepage:  http://designmodo.com/linecons-free/
// /// * Iconic, Copyright (C) 2012 by P.J. Onori
// ///         Author:    P.J. Onori
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://somerandomdude.com/work/iconic/
// /// * Linearicons Free, Copyright (C) Linearicons.com
// ///         Author:    Perxis
// ///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
// ///         Homepage:  https://linearicons.com
// /// * RPG Awesome, Copyright (c) 2014, Daniela Howe
// ///         Author:    Daniela Howe & Ivan Montiel
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
// /// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
// ///         Author:    MFG Labs
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://www.mfglabs.com/
// /// * Octicons, Copyright (C) 2020 by GitHub Inc.
// ///         Author:    GitHub
// ///         License:   MIT (http://opensource.org/licenses/mit-license.php)
// ///         Homepage:  https://primer.style/octicons/
// ///
// import 'package:flutter/widgets.dart';

// class RemottelyIcons {
//   RemottelyIcons._();

//   static const _kFontFam = 'RemottelyIcons';
//   static const String? _kFontPkg = null;

//   static const IconData ok =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ok_circle =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData check_1 =
//       IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ok_circled =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData settings =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_filled =
//       IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart =
//       IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basket =
//       IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basket_1 =
//       IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag =
//       IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart_plus_2 =
//       IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_basket_1 =
//       IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart_arrow_down =
//       IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_1 =
//       IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_2 =
//       IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData location_on =
//       IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shop =
//       IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bookmark_border =
//       IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bookmark =
//       IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData minus =
//       IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData minus_1 =
//       IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add_circle_outline =
//       IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData remove_circle =
//       IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData remove_circle_outline =
//       IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData remove =
//       IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData library_add =
//       IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add_to_photos =
//       IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add_box =
//       IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add_circle =
//       IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData title =
//       IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cw =
//       IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cw_1 =
//       IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cached =
//       IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData history =
//       IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData checkmark_cicle =
//       IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData crowned_heart =
//       IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gear_heart =
//       IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData glass_heart =
//       IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hearts =
//       IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ccw =
//       IconData(0xf025, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData check_circle =
//       IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_cart =
//       IconData(0xf07a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData users =
//       IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_md =
//       IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dollar =
//       IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData google =
//       IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart_plus =
//       IconData(0xf217, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart_arrow_down_2 =
//       IconData(0xf218, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_secret =
//       IconData(0xf21b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_plus =
//       IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_times =
//       IconData(0xf235, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag =
//       IconData(0xf290, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_basket_2 =
//       IconData(0xf291, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData checklist =
//       IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shield_check =
//       IconData(0xf33e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData check =
//       IconData(0xf369, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_alt =
//       IconData(0xf406, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_alt_slash =
//       IconData(0xf4fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_astronaut =
//       IconData(0xf4fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_check =
//       IconData(0xf4fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_clock =
//       IconData(0xf4fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_cog =
//       IconData(0xf4fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_edit =
//       IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_friends =
//       IconData(0xf500, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_lock =
//       IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_minus =
//       IconData(0xf503, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_shield =
//       IconData(0xf505, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_tag =
//       IconData(0xf507, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_tie =
//       IconData(0xf508, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData users_cog =
//       IconData(0xf509, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData door_closed =
//       IconData(0xf52a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
